[tool.poetry]
name = "scissorsgame"
version = "0.1.0"
description = "Scissors game"
authors = ["O. Rubanov <rub.alex7328@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
